---
development:
  cloud_name: action
  api_key: '163215746553324'
  api_secret: 3pDIZnvpEGeY-PqhNx9qfMsr03M
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: action
  api_key: '163215746553324'
  api_secret: 3pDIZnvpEGeY-PqhNx9qfMsr03M
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: action
  api_key: '163215746553324'
  api_secret: 3pDIZnvpEGeY-PqhNx9qfMsr03M
  enhance_image_tag: true
  static_image_support: false
